import mongoose from "mongoose";

const walletTransactionSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    // ============= ORDER IDENTIFIERS =============
    // Unique order ID generated by your system
    orderId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },

    // CCAvenue tracking ID (returned after payment)
    trackingId: {
      type: String,
      default: null,
      index: true,
    },

    // Bank reference number (returned after successful payment)
    bankRefNo: {
      type: String,
      default: null,
    },

    // ============= AMOUNTS =============
    // Total amount paid by customer
    grossAmount: {
      type: Number,
      required: true,
      min: 1,
    },

    // Amount to be credited to wallet (e.g., 80% of gross)
    walletCreditAmount: {
      type: Number,
      required: true,
    },

    // Platform fee (e.g., 20% of gross)
    platformFeeAmount: {
      type: Number,
      required: true,
    },

    currency: {
      type: String,
      default: "INR",
    },

    // ============= STATUS =============
    status: {
      type: String,
      enum: ["CREATED", "PAID", "FAILED", "ABORTED", "INVALID", "TIMEOUT"],
      default: "CREATED",
      index: true,
    },

    // CCAvenue order status (raw from response)
    ccavenueOrderStatus: {
      type: String,
      default: null,
    },

    // Failure message from CCAvenue
    failureMessage: {
      type: String,
      default: null,
    },

    // ============= PAYMENT DETAILS =============
    paymentMode: {
      type: String,
      default: null,
    },

    cardName: {
      type: String,
      default: null,
    },

    // Status code from CCAvenue
    statusCode: {
      type: String,
      default: null,
    },

    // Status message from CCAvenue
    statusMessage: {
      type: String,
      default: null,
    },

    // ============= METADATA =============
    // Payment gateway identifier
    paymentGateway: {
      type: String,
      default: "ccavenue",
    },

    // Raw response from CCAvenue (for debugging)
    rawResponse: {
      type: Object,
      default: null,
    },

    // Transaction date from CCAvenue
    transDate: {
      type: String,
      default: null,
    },

    // When wallet was credited
    creditedAt: {
      type: Date,
      default: null,
    },

    // ============= BILLING INFO (Optional - stored for records) =============
    billingInfo: {
      name: String,
      email: String,
      phone: String,
      address: String,
      city: String,
      state: String,
      zip: String,
      country: String,
    },
  },
  { timestamps: true }
);

// ============= INDEXES =============
walletTransactionSchema.index({ user: 1, status: 1 });
walletTransactionSchema.index({ createdAt: -1 });
walletTransactionSchema.index({ trackingId: 1 }, { sparse: true });

// ============= METHODS =============
walletTransactionSchema.methods.markAsPaid = function (responseData) {
  this.status = "PAID";
  this.trackingId = responseData.tracking_id;
  this.bankRefNo = responseData.bank_ref_no;
  this.ccavenueOrderStatus = responseData.order_status;
  this.paymentMode = responseData.payment_mode;
  this.cardName = responseData.card_name;
  this.statusCode = responseData.status_code;
  this.statusMessage = responseData.status_message;
  this.transDate = responseData.trans_date;
  this.rawResponse = responseData;
  this.creditedAt = new Date();
  return this.save();
};

walletTransactionSchema.methods.markAsFailed = function (responseData) {
  this.status = "FAILED";
  this.trackingId = responseData.tracking_id;
  this.ccavenueOrderStatus = responseData.order_status;
  this.failureMessage = responseData.failure_message;
  this.paymentMode = responseData.payment_mode;
  this.cardName = responseData.card_name;
  this.statusCode = responseData.status_code;
  this.statusMessage = responseData.status_message;
  this.transDate = responseData.trans_date;
  this.rawResponse = responseData;
  return this.save();
};

walletTransactionSchema.methods.markAsAborted = function (responseData) {
  this.status = "ABORTED";
  this.trackingId = responseData.tracking_id;
  this.ccavenueOrderStatus = responseData.order_status;
  this.failureMessage = responseData.failure_message || "Transaction cancelled by user";
  this.rawResponse = responseData;
  return this.save();
};

export default mongoose.model("WalletTransaction", walletTransactionSchema);
